ANALYTICS-2214 : Provide disable feature for the sidebar node
Webtrekk/Ampel-UI pull request #84
Opened 2020-10-30 08:43 UTC by efekaptan

Provides the disabled behaviour for a sidebar node. Optional disableMessage shown as a Tooltip to the user.

2020-10-30 08:57 UTC, x057 approved these changes
Looks good to me

2020-10-30 09:21 UTC, manojkrishna1991 approved these changes

2020-10-30 10:21 UTC, BenjaminEckardt commented
Besides the missing test it also looks good to me.

2020-11-02 09:19 UTC, BenjaminEckardt requested changes

2020-11-02 10:33 UTC, efekaptan commented on src/tree/node.tsx
> +                    {node.disabled && node.disabledMessage ? (
@BenjaminEckardt ok

2020-11-03 13:51 UTC, BenjaminEckardt approved these changes

2020-11-03 14:05 UTC, merged